PrincetonPEMM/pemm-website

src/components/common/navbar.tsx, src/pages/stories/index.tsx
- Changed text formatting to better highlight headers, navigations and important information
=> fixing text formatting

src/components/elements/advancedSearchComponent.tsx, src/components/elements/storiesTableComponent.tsx
=> made several ui fixes

.gitignore, src/pages/stories/[canonicalId].tsx
- Created empty components for Ayo and Issac's tickets
- Added some files to gitignore
=> Created empty components and added stuff to the gitignore

src/lib/ga/index.js, src/pages/_app.tsx, src/pages/_document.tsx
- Adding google analytics to track page views in our application
=> Adding Google Analytics fro page views

src/pages/stories/[canonicalId].tsx
- Made the story detail page mobile friendly by introducing tabs to the text area
=> Making story detail page mobile friendly

src/components/elements/storiesTableComponent.tsx, src/components/types/filter_data.ts, src/pages/stories/index.tsx, src/utils/table_filter.ts
- Added a filter bar to the story index page
=> Filter story by text

src/components/elements/generatedStoryText.tsx, src/data/story13.ts
Wrote outline and made function to work out logic of some of the generated text sections. Bracketed letters indicate locations where generated text will be put to complete phrases.
=> Edits to generated story text information

src/pages/stories/[canonicalId].tsx
Fixing bug in getting story index from story detail page
=> Fixing bug in getting story index from story detail page

next.config.js, src/components/elements/imageTextComponent.tsx, src/components/elements/imagesComponent.tsx, src/components/types/paintings.ts, src/pages/paintings.tsx
- Made paintings in paintings page into mat cards
- Added manuscript and episode keywords information
- Added read more link to navigate to story detail page
=> Updated paintings page

src/pages/stories/[canonicalId].tsx
Adding the story cycle component to the mobile view of story detail page
=> Add story cycle to mobile

package-lock.json, src/components/common/footer.tsx, src/components/elements/embeddedMap.tsx, src/pages/_document.tsx, src/pages/maps.tsx
- Added the 'Maps' page hyperlink to the footer
- Embedded the Tableau map on the 'Maps' page
- TODO: Connect the Tableau worksheet to JSON from the 'Manuscript' PEMM database
=> Embedded Tableau Map on the Maps Page

src/pages/maps.tsx
Fixing tableau script import bug
=> Fixing tableau script import bug

src/components/elements/storyChips.tsx, src/utils/table_filter.ts
Making fixes to the languages of story filter
=> Making fixes to the languages of story filter

package-lock.json, package.json
Installing Sharp as per next recommendation
https://nextjs.org/docs/messages/sharp-missing-in-production
=> Installing Sharp as per next recommendation

package-lock.json, package.json, src/pages/paintings.tsx
- Making paintings page static
- Removing some dump/risky string parsing
- Adding error message
=> Making paintings page static

src/components/elements/cycleHyperlink.tsx, src/components/elements/generatedStoryText.tsx, src/components/types/stories.ts, src/data/stories.ts, src/data/story13.ts, src/pages/api/stories/stories_cycle.ts, src/pages/stories/[canonicalId].tsx
- optimize story detail page by switching to get a lighter all stories api
- switching pemm_id field to be a number type to fix sorting for story cycles
=> optimize story detail page

src/components/common/navbar.tsx
=> Adding development banner

src/components/types/manuscripts.ts, src/data/manuscript1.ts, src/pages/api/manuscripts/[manuscriptId].ts, src/pages/manuscripts/[manuscriptId].tsx, src/pages/manuscripts/index.tsx
- Setup manuscript detail page
- Created initial api for manuscript detail that returns manuscript detail and  manuscript id for the given manuscript id
- Created mock data file for development purposes
=> Setup manuscript detail page

src/components/common/navbar.tsx
- Adding this site is under development banner
=> Adding still under development banner

src/components/elements/generatedStoryText.tsx, src/components/elements/storyChips.tsx, src/utils/table_filter.ts
- Some updates made during call with wendy
=> Wendy henok updates 12 9

src/components/elements/storyTranslationAndCitation.tsx, src/components/types/stories.ts, src/data/story13.ts
-Updated code for citations of other translations to pull from translations sheet instead of canonical story sheet 
-Currently uses manually input dev data for story 13 to confirm code logic
- Translations data needs to be added to the website API
=> Updated Other Translation Citations

src/components/types/paintings.ts
Adding these fields to Paintings type:
painting_date : is a number
is_black_and_white: is a boolean(true or false)
painting_available: is a boolean(true or false)
type_of_story: string that can only be "Life of Mary" or "Miracle of Mary"
=> Adding painting fields for dropdown

src/components/elements/generatedStoryText.tsx, src/data/story13.ts
The translations sentence has been updated to pull from the Translations sheet, as per Ticket #97.
Has been successfully tested with the API dev data.
=> Updated Translation Sentence - Story Detail Page

src/components/elements/generatedStoryText.tsx, src/data/story13.ts
Reverts PrincetonPEMM/pemm-website#97
=> Revert "Updated Translation Sentence - Story Detail Page"
